image: archlinux
packages:
  - go
sources:
  - https://git.sr.ht/~mariusor/motley
environment:
  GO111MODULE: 'on'
secrets:
  - 3dcea276-38d6-4a7e-85e5-20cbc903e1ea
tasks:
  - build: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      cd motley
      make download && make clean all
  - tests: |
      cd motley
      make test
  - push_to_github: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      cd fedbox
      git remote add hub git@github.com:mariusor/motley
      git push hub --force --all
